[package]
name = "sonata"
version = "0.1.0"
edition = "2024"

[dependencies]
rodio = "0.21.1"
reqwest = { version = "0.10.10", features = ["blocking"] }
symphonia = { version = "0.5", features = ["all"] }
